### ISSUE TITLE
Edit the Message Controller getContacts

### ISSUE THREAD

**Issue by latestbob** [munafio/chatify-demo#10]
Hi,,, I have successfully integrated Chatify,,, its a great work,.,,  but in the MessageController that comes as result of publishing the config files,, I can't see the effect of changes made there..

Lets say in the searchUser,  I want the get users where column a is equal to Auth::user()->column a

Tried it didn't see my changes, even tried to remove the code, didn't see changes of error code... How can I solve it 
![ksnkdfnlkd](https://user-images.githubusercontent.com/42245675/99417958-c95a3780-28fa-11eb-9045-78b2cf52a6dd.PNG)
![kdkdlkfedfd](https://user-images.githubusercontent.com/42245675/99417976-cfe8af00-28fa-11eb-9a57-d6591bf8f56b.PNG)

**Comment by munafio** [comment]
@latestbob Please check out **Controllers' Namespace** configuration mentioned in the docs here :
https://github.com/munafio/chatify#controllers-namespace

**Comment by kiet19992020** [comment]
![1](https://user-images.githubusercontent.com/59956799/121899871-03839e80-cd4f-11eb-897a-2680f296b363.PNG)
![2](https://user-images.githubusercontent.com/59956799/121899875-04b4cb80-cd4f-11eb-81a1-d19f3e84c9b2.PNG)
hi admin, I have successfully installed chatify, but my message delivery bar is not displayed

**Comment by munafio** [comment]
@kiet19992020 First, check out the console and provide more details about your issue.
Second, as I can see in the first picture that you have published the controllers but missed to change the name space as mentioned in the docs, so please follow the official documentation at ’customizations’ section.

**Comment by kiet19992020** [comment]
@munafio hello Admin, I installed under 'Customizations', tried uninstalling and reinstalling the app many times, but the result is still can't use the messages. Thank you for the support from this.
![1](https://user-images.githubusercontent.com/59956799/122012258-2b264580-cde7-11eb-9864-2590ecf4b405.PNG)
![2](https://user-images.githubusercontent.com/59956799/122012263-2cf00900-cde7-11eb-8dc3-7c391ea219a8.PNG)
![3](https://user-images.githubusercontent.com/59956799/122012264-2cf00900-cde7-11eb-8ded-1b90c7ed7240.PNG)
![4](https://user-images.githubusercontent.com/59956799/122012267-2d889f80-cde7-11eb-89fe-378201b5abfa.PNG)





-

**Comment by munafio** [comment]
@kiet19992020 Please, open a new issue describes what you are facing, and provide more information with the pictures above (e.g. Laravel , Chatify , php version...) and  how you have installed the package.

**Comment by kiet19992020** [comment]
@munafio  sorry ^^!, I'm having trouble not showing the chat bar on the app, and I installed the following youtube instructions from your channel.  (https://chatify.munafio.com/), (Install Chatify v1.2 | Laravel Real-time chat package).Thanks for the support.
![1](https://user-images.githubusercontent.com/59956799/122155063-64ff5680-ce90-11eb-9065-ec74ba12a681.PNG)

![2](https://user-images.githubusercontent.com/59956799/122155136-895b3300-ce90-11eb-873e-09dfd4bd2a19.PNG)

**Comment by kiet19992020** [comment]
@munafio, I'm having trouble not showing the chat bar on the app and I installed the following youtube tutorial from your channel. (https://chatify.munafio.com/), (Install Chatify v1.2 | Laravel Realtime Chat Package). I really need this function, please help me.

**Comment by munafio** [comment]
@kiet19992020 you may have an error, if any error occured then the chat will not be opened or showed!
Check your console logs and network tab.

**Comment by kiet19992020** [comment]
@munafio  
This is the message from the control panel, a network tab, I still download and install it according to the instructions, the previous version I used is v1 without any errors, I tried deleting and reinstalling, but the error still doesn't work overcome. all the screens I mentioned above. thanks for your help.

**Comment by munafio** [comment]
@kiet19992020  Join the [Discord](https://discord.gg/RaxyKVykYJ) if you need a help installing Chatify.

**Comment by kiet19992020** [comment]
I fixed this error, by running the following commands
so what you need to do now is to re-publish the assets by the following commands:
- php artisan verndor:publish --tag=chatify-views --force
- php artisan verndor:publish --tag=chatify-assets --force
- php artisan verndor:publish --tag=chatify-migrations --force
