### ISSUE TITLE
Bug stored xss in message area 

### ISSUE THREAD

**Issue by Jieyab89** [munafio/chatify-demo#11]
Hello, 

Nice Project, but i founded bug in your package 

Hello, I found an xss bug in the chat textarea, I checked the code already has htmlspecialchars, but the payload can still be executed,

Thank you

**Comment by Jieyab89** [comment]
![image](https://user-images.githubusercontent.com/71226310/100041727-7f161080-2e3c-11eb-8b23-196bc4e42246.png)
![image](https://user-images.githubusercontent.com/71226310/100041771-9ce37580-2e3c-11eb-8407-bf17e0ecf045.png)

**Comment by Jieyab89** [comment]
If the system is already right, only when it parses from append input to chat it has an xss bug

**Comment by munafio** [comment]
Hi @Jieyab89 ,
I'll check this issue and fix it ASAP.
Thanks a lot for your efforts to make this package better.

**Comment by Jieyab89** [comment]
Solved, im fix xss in chat message, im create function for encoding 

//create like htmlspecialchars in js
function escapeHtml(text) {
  var map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  
  return text.replace(/[&<>"']/g, function(m) { return map[m]; });
}

**Comment by Jieyab89** [comment]
in file code.js

**Comment by Jieyab89** [comment]
![image](https://user-images.githubusercontent.com/71226310/100430539-80a83880-30c9-11eb-904e-4e631a8becbd.png)
Create function htmlescape in code.js 

Code : 
//create like htmlspecialchars in js
function escapeHtml(text) {
    var map = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;'
    };
    
    return text.replace(/[&<>"']/g, function(m) { return map[m]; });
  }
after you create the function you can call it, and call the function as needed,

For example, I called the htmlescape function in the message text area. You can check this

Example : 

//create like htmlspecialchars in js
function escapeHtml(text) {
    var map = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;'
    };
    
    return text.replace(/[&<>"']/g, function(m) { return map[m]; });
  }
  
// While sending a message, show this temporary message card.
function sendigCard(message, id) {
    const body = escapeHtml(message);
    return `
    <div class="message-card mc-sender" data-id="`+ id + `">
        <p>`+ body + `<sub><span class="far fa-clock"></span></sub></p>
    </div>
    `;
}

**Comment by Jieyab89** [comment]
Thank you munafio
