### ISSUE TITLE
Target class [MessagesController] does not exist.

### ISSUE THREAD

**Issue by jalallinux** [munafio/chatify-demo#14]
Target class [MessagesController] does not exist.

https://flareapp.io/share/qm1rblrP

**Comment by jamesof** [comment]
Hi there, starting with Laravel 8, the `App\Http\Controllers` namespace is no longer automatically available (it is set to null). As per the docs: "This allows your controller route declarations to use the standard PHP callable syntax, which provides better support for jumping to the controller class in many IDEs". See [here](https://laravel.com/docs/8.x/upgrade#automatic-controller-namespace-prefixing)  for more info

To fix this issue, simply import the MessagesController class via `use` keyword or use the fully qualified namespace i.e `\Chatify\Http\Controllers\MessagesController` in all the routes. Note the file to edit is: `path-to-your-project/vendor/munafio/chatify/routes/web.php`

**Comment by developers4p2g** [comment]
Hi @jamesof 
I'm using the Laravel 6, and facing same above problem.
See Screenshot: https://prnt.sc/yua221

**Comment by munafio** [comment]
@jamesof @developers4p2g 
duplicated #46 + #62

**Comment by munafio** [comment]
@jamesof @developers4p2g Please check out these links on the official package's repository, which has discussed and solved your issue before: 
Issue No. 46: https://github.com/munafio/chatify/issues/46
Issue No. 62: https://github.com/munafio/chatify/issues/62
