### ISSUE TITLE
Display issue with Demo

### ISSUE THREAD

**Issue by Minhaj9800** [munafio/chatify-demo#26]
I am trying to run the demo but it is going to the Laravel Official Documentation page.[
![Screenshot from 2021-06-18 00-48-58](https://user-images.githubusercontent.com/36388349/122503549-08568580-cfcf-11eb-880e-55df00b0c1e3.png)
](url)

**Comment by munafio** [comment]
@Minhaj9800 This is not the docs page, this is the main page of the app and you can see at the top right of the page (login,register) 

Login or register then go to `/chatify`
