### ISSUE TITLE
Can't see chat box or favorite chat user

### ISSUE THREAD

**Issue by cheema14** [munafio/chatify-demo#50]
Hi! 
I installed the demo as per the instructions. I am running it on my local server and have successfully logged in. 
But There's a blank page and nothing on it. The other links which I can see are
Profile and dashboard. But there are no chat links. 
Can you look into it? Did I miss something?

**Comment by eriktailor** [comment]
You have to use a route `/chatify` to show the chat... not obvious for me neither 😆

**Comment by munafio** [comment]
@eriktailor @cheema14 If you guys did not read the official documentation of [Chatify](https://chatify.munafio.com/) then you'll not figure it out.. the messenger should be accessed by it's prefix `/chatify`
