### ISSUE TITLE
Getting error like 'No internet access' & Always reload page is required

### ISSUE THREAD

**Issue by Pream-webapps** [munafio/chatify-demo#51]
Dear team, I appreciate your efforts, but unfortunately, the work is not meeting the expected outcomes. If feasible, please make an attempt to resolve this issue.
SS attached

![image](https://github.com/munafio/chatify-demo/assets/30262359/46c7ab35-2bb7-488d-b5bc-818c94d5c57b)
![image](https://github.com/munafio/chatify-demo/assets/30262359/cad00827-5bbe-40eb-84eb-5ac9a0bb5c82)

**Comment by munafio** [comment]
Please make sure of the credentials of Pusher are correct and checkout the logs/network to check if its connected or something went wrong
