### ISSUE TITLE
Does not display users in "All Messages"

### ISSUE THREAD

**Issue by amna-kamran** [munafio/chatify-demo#53]
1. Something is missing in app.blade.layout for chatify under the {{-- ---------------- [ User Tab ] ---------------- --}} 

`<p class="messenger-title"><span>All Messages</span></p>
               <div class="listOfContacts" style="width: 100%;height: calc(100% - 272px);position: relative;"></div>` within this code.

2. There should be something like `{!! view('Chatify::layouts.listItem', ['get' => 'users', 'lastMessage' => $lastMessage]) !!}` but I'm not sure where to get the $lastmessage from.

**Comment by munafio** [comment]
1. I see nothing is missing there! if Im not correct then please correct me.
2. You should get it from the controller itself
