### ISSUE TITLE
changing user profile from avatar

### ISSUE THREAD

**Issue by daniel-teddy** [munafio/chatify-demo#55]
I was wondering having a database where each user has a profile_picture, I want to use it as the avatar specified in chatify, anyone can hepl me achieve this ? I see that its being set with javascript after making a request with ajax
`$.ajax({
      url: url + "/idInfo",
      method: "POST",
      data: { _token: csrfToken, id },
      dataType: "JSON",
      
      success: (data) => {
        if (!data?.fetch) {
          NProgress.done();
          NProgress.remove();
          return;
        }
        // avatar photo
        $(".messenger-infoView")
          .find(".avatar")
          .css("background-image", 'url("' + data.user_avatar + '")');
          console.log("data"),
        $(".header-avatar").css(
          "background-image",
          'url("' + data.user_avatar + '")'
        );`

**Comment by munafio** [comment]
@teddy-webdev simply you can modify `idFetchData` method's response to return your specified avatar instead of what Chatify does. 
The method available at MessagesController of Chatify, you need to publish the controller to be able to modify. Read the official documentation
