### ISSUE TITLE
Did not received messages real-time !! 

### ISSUE THREAD

**Issue by gurpreetindybytes** [munafio/chatify-demo#6]
I have installed this package and follow all instructions. chat is working fine but messages only displayed after refreshing the page. Can you please help me to fix this issue.

**Comment by munafio** [comment]
Please, open the inspector and track if any errors occurred there to provide!

**Comment by mohammadsalmani28** [comment]
I have this problem too...
problem is in Vue...
browser console  report an error : cannot find element app

**Comment by mohammadsalmani28** [comment]
I found solution in original installation in link below:
[https://github.com/munafio/chatify](https://github.com/munafio/chatify)
problem is about publishing assets.
after publish assets problem solved.
the installation in demo is not complete!
@munafio @gurpreetindybytes

**Comment by munafio** [comment]
@mohammadsalmani28 I'll mention that in the installation steps of this demo app.
