### ISSUE TITLE
javascript not load i.e chatify:329 Uncaught ReferenceError: $ is not defined  at chatify:329

### ISSUE THREAD

**Issue by kathmandu1** [munafio/chatify-demo#7]
i install a package and publish all assects,migration and config, when i hit url localhost:8000/chatify ui appear but javascript not run 
shows errors 
chatify:329 Uncaught ReferenceError: $ is not defined
    at chatify:329
(anonymous) @ chatify:329
code.js:12 Uncaught ReferenceError: $ is not defined
    at code.js:12

**Comment by munafio** [comment]
I think you don't have jQuery installed in your app, It is required by the package.
