### ISSUE TITLE
After Send message receiver need to reload page!! pusher not working properly 

### ISSUE THREAD

**Issue by shoaib0906** [munafio/chatify-demo#8]
Laravel 6
Php 7.2

FIrst of all thanks a lot for such a wonderfull chat package i have integrate this with my events management platform and need you help to grow.

After sending text console shows this error

Pusher : Event recd : {"event":"pusher:error","data":{"code":null,"message":"To send client events, you must enable this feature in the Settings page of your dashboard."}}
pusher.min.js:8 Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"To send client events, you must enable this feature in the Settings page of your dashboard."}}}

i tried with bootstrap.js::

import Echo from 'laravel-echo';
window.Pusher = require('pusher-js');
window.Echo = new Echo({
     broadcaster: 'pusher',
     key: process.env.MIX_PUSHER_APP_KEY,
     cluster: process.env.MIX_PUSHER_APP_CLUSTER,
     encrypted: true
 });

my app.js and bootstrap.js
[app.zip](https://github.com/munafio/chatify-demo/files/5171952/app.zip)

**Comment by munafio** [comment]
You probably not followed the installation steps as mentioned! .. 
The error says:
`"To send client events, you must enable this feature in the Settings page of your dashboard."`

So, You need to enable `client-events` in your pusher account settings as mentioned in the docs ([Step 2](https://github.com/munafio/chatify#2-pusher-api-settings))
